# Generated by Django 6.1 on 2026-08-17 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='false면 예약 목록에서 제외')),
            ],
            options={
                'db_table': 'store',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='UNIQUE, 로그인 아이디로 사용', max_length=254, unique=True)),
                ('nickname', models.CharField(help_text='UNIQUE', max_length=30, unique=True)),
                ('provider', models.CharField(choices=[('email', '이메일'), ('kakao', '카카오'), ('naver', '네이버')], default='email', help_text='email / kakao / naver', max_length=10)),
                ('social_id', models.CharField(blank=True, help_text='소셜 로그인 시 발급되는 식별자', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='탈퇴 시 false 처리')),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_at', models.DateTimeField(help_text='예약 가능 날짜·시간만')),
                ('status', models.CharField(choices=[('confirmed', '예약완료'), ('changed', '변경됨'), ('canceled', '취소됨')], default='confirmed', help_text='confirmed / changed / canceled', max_length=20)),
                ('guest_id', models.CharField(blank=True, help_text='비로그인 예약 시 필수', max_length=100, null=True)),
                ('guest_password', models.CharField(blank=True, help_text='비로그인 예약 시 필수, 해시 저장', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='USER 참조. 비로그인 예약 시 NULL', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='accounts.store')),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('social_id__isnull', False)), fields=('provider', 'social_id'), name='unique_social_account'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('store', 'reserved_at'), name='unique_store_time'),
        ),
    ]
