# Generated by Django 6.1 on 2026-08-18 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('maker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wishlist',
            name='unique_user_product_wish',
        ),
        migrations.AddField(
            model_name='store',
            name='close_time',
            field=models.TimeField(blank=True, help_text='영업 종료 시각', null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='open_time',
            field=models.TimeField(blank=True, help_text='영업 시작 시각', null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='decoration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='decoration_wishlists', to='maker.component'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='knot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='knot_wishlists', to='maker.component'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='tassel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tassel_wishlists', to='maker.component'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(fields=('user', 'knot', 'tassel', 'decoration'), name='unique_user_product_wish'),
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
    ]
