# Generated by Django 6.1 on 2026-08-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_wishlist_unique_user_product_wish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, help_text='성명. 소셜 가입은 나중에 채움', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='전화번호. 소셜 가입은 나중에 채움', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, help_text='UNIQUE. 가입 후 마이페이지에서 설정', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='social_id',
            field=models.CharField(blank=True, help_text='소셜 로그인 식별자', max_length=255, null=True),
        ),
    ]
