# Generated by Django 6.1 on 2026-08-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_name_user_phone_alter_user_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='프로필 사진', null=True, upload_to='profiles/'),
        ),
    ]
