# Generated by Django 6.1 on 2026-08-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_profile_image'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservation',
            name='unique_store_time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_no',
            field=models.CharField(blank=True, help_text='예약번호 MCM-연도-4자리. 생성 시 자동', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_id',
            field=models.CharField(blank=True, help_text='비로그인 예약 시 필수. 이메일로 사용', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('confirmed', '예약완료'), ('changed', '변경됨'), ('canceled', '취소됨')], default='confirmed', max_length=20),
        ),
    ]
