# Generated by Django 6.1 on 2026-08-11 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("knot", "매듭"),
                            ("tassel", "술"),
                            ("decoration", " 장식"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "color",
                    models.CharField(
                        blank=True, help_text="기본 대표 색상", max_length=20, null=True
                    ),
                ),
                (
                    "meaning",
                    models.TextField(
                        blank=True,
                        help_text="전통 상징 의미-AI 추천/설명 근거 데이터",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "component",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.IntegerField(help_text="가격(원)")),
                ("image_url", models.CharField(blank=True, max_length=255, null=True)),
                ("mcm_link", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "product",
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="2026 여름", max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
            options={
                "db_table": "season",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wish_keyword",
                    models.CharField(help_text="입력한 바람/키워드", max_length=100),
                ),
                (
                    "symbol_reason",
                    models.TextField(
                        blank=True,
                        help_text="AI가 준 상징 추천 이유 (최초 생성 후 고정, 재갱신 안 됨)",
                        null=True,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="사용자가 고른 전체 색상",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True,
                        help_text="저장된 이미지 경로",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decoration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decoration_items",
                        to="maker.component",
                    ),
                ),
                (
                    "knot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="knot_items",
                        to="maker.component",
                    ),
                ),
                (
                    "tassel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tassel_items",
                        to="maker.component",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="팀원의 User 모델 참조. 비로그인 임시저장 시 NULL",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "item",
            },
        ),
        migrations.AddField(
            model_name="component",
            name="season",
            field=models.ForeignKey(
                blank=True,
                help_text="시즌 한정이면 연결, 상시 판매면 NULL",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="components",
                to="maker.season",
            ),
        ),
    ]
