# Generated by Django 6.1 on 2026-08-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="description",
            field=models.CharField(
                blank=True, help_text="조합 설명 문구", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="title",
            field=models.CharField(
                blank=True, help_text="조합 제목", max_length=100, null=True
            ),
        ),
    ]
