# Generated by Django 6.1 on 2026-08-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maker", "0002_item_description_item_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="image_url",
            field=models.CharField(
                blank=True,
                help_text="레이어 조립용 에셋 경로",
                max_length=255,
                null=True,
            ),
        ),
    ]
