# Generated by Django 6.1 on 2026-08-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maker", "0002_alter_component_id_alter_item_id_alter_product_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="tassel",
        ),
        migrations.AddField(
            model_name="item",
            name="tassel_count",
            field=models.IntegerField(
                choices=[(1, "1개"), (2, "2개"), (3, "3개")],
                default=1,
                help_text="술 개수 (1~3개)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="component",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
