# Generated by Django 6.1 on 2026-08-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maker", "0003_remove_item_tassel_item_tassel_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="feature_name",
            field=models.CharField(
                blank=True,
                help_text="시즌 상징 갤러리용 표시 이름 - name(에디터용)과 다를 수 있음",
                max_length=100,
                null=True,
            ),
        ),
    ]
