# Generated by Django 6.1 on 2026-08-16 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maker", "0003_component_image_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="feature_image_url",
            field=models.CharField(
                blank=True,
                help_text="시즌 상징 섹션 등 프로모션용 별도 이미지 (시즌 한정 항목에만 값 채워짐)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="type",
            field=models.CharField(
                choices=[("knot", "매듭"), ("tassel", "술"), ("decoration", "장식")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="디자인 저장은 로그인 필수라 항상 채워짐. null 허용은 과거 설계 흔적, 마이그레이션 부담 피하려 스키마는 그대로 둠",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
