# Generated by Django 6.1 on 2026-08-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maker", "0004_component_feature_image_url_alter_component_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="mcm_link",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
