# Generated by Django 6.1 on 2026-08-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maker", "0005_alter_product_image_url_alter_product_mcm_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="feature_description",
            field=models.CharField(
                blank=True,
                help_text="시즌 상징 갤러리용 설명 문구 - meaning(전통 의미)과 별개, 마케팅 톤. 시즌 한정 항목에만 값 채워짐",
                max_length=255,
                null=True,
            ),
        ),
    ]
